name: notificacoes_locais
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  device_info_plus: ^11.4.0
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.2.1
  flutter_timezone: ^4.1.1
  http: ^1.4.0
  image: ^4.5.4
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
